### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nejdetckenobi** [nllptr/pyban#2]
Instructions are not enough. I couldn't run it. Please explain more.

**Comment by nllptr** [comment]
First of all, PyBan is written in python3, so check that you have it installed. Python2 will not work.
Secondly, PyBan requires curses/ncurses, so you will have to install that too. I believe you need the libraries for your operating system as well as the python library.
I have not touched this project in a very long time, and I will not have the time to work on it. If you think you'll find it useful, I'd be glad to hand the project over to you.

**Comment by nejdetckenobi** [comment]
I missed the part of Python3 (or couldn't see in docs). Thanks. Now it's working.
Just checking kanban alternatives for terminal. I'll fork it if I had enough time to improve it. 
Thanks again.

**Comment by nllptr** [comment]
Thanks for being patient. The python3 part is probably not in the docs. I'll add it.
